# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MacCleanupGo < Formula
  desc "Interactive TUI for cleaning macOS caches, logs, and temporary files"
  homepage "https://github.com/2ykwang/mac-cleanup-go"
  version "1.3.8"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/2ykwang/mac-cleanup-go/releases/download/v1.3.8/mac-cleanup-go_1.3.8_darwin_amd64.tar.gz"
    sha256 "b907306ae46235822c30b4cf9d21559b1b31a139e4b1aa7d1bf79731aa37539a"

    def install
      bin.install "mac-cleanup"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/2ykwang/mac-cleanup-go/releases/download/v1.3.8/mac-cleanup-go_1.3.8_darwin_arm64.tar.gz"
    sha256 "e35de9acfad8f036f993f5bf856297414f78cb6701e025c46c5e9ffe48edad56"

    def install
      bin.install "mac-cleanup"
    end
  end

  test do
    system "#{bin}/mac-cleanup", "--version"
  end
end
